name: Daily Test

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm init -y && npm install playwright

      - run: npx playwright install --with-deps

      - env:
          SUB3_HOLYWAR_JS: ${{ secrets.SUB3_HOLYWAR_JS }}
        run: |
          echo "$SUB3_HOLYWAR_JS" > sub3_holywar.js
          node sub3_holywar.js
